### ISSUE TITLE
documentation: local-provisioner comparison

### ISSUE THREAD

**Issue by yanniszark** [openshift/local-storage-operator#1]
Hello everyone! :hand: 

I'm very interested in using local storage in Kubernetes for applications like distributed databases. I am currently developing an [operator for Cassandra and ScyllaDB](https://rook.io/docs/rook/v0.9/cassandra.html) with rook and both of those databases would benefit greatly from using local storage. 

I am wondering what's the difference between this project and [local volume provisioner](https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner). I would love to know the scope of the project and see if it aligns with my goals, so that I can also contribute to it. :smile:

**Comment by j-griffith** [comment]
Hi @yanniszark  very late response... but; the main thing is this project provides an operator to automate the setup, configuration and deployment of local disks "for you".  It will create the PV's and the SC with the appropriate affinity settings.  Hope that helps, in case you notice the response.
