### ISSUE TITLE
[RFE] Automate or document cleanup.

### ISSUE THREAD

**Issue by rohantmp** [openshift/local-storage-operator#115]
Current:
AFAIK, there is not documentation or automation for cleaning symlinks on nodes.
Creating a LocalVolume with a previous StorageClass name after reinstalling LSO will result in old disks (now referred to by no LocalVolumes) being provisioned.

Expected:

There should be documentation or automation for cleaning symlinks on nodes.

Opening because I've seen multiple people run into this issue recently.

**Comment by bobfuru** [comment]
Hi @rohantmp - Please see step 3 here about how to delete symlinks on the node:
https://docs.openshift.com/container-platform/4.4/storage/persistent_storage/persistent-storage-local.html#deleting-the-local-storage-operators-resources

Let me know if that addresses the issues you've been seeing. Thanks!
