### ISSUE TITLE
local-storage-operator needs POD_NAME environment variable

### ISSUE THREAD

**Issue by ibotty** [openshift/local-storage-operator#119]
Using https://github.com/openshift/local-storage-operator/blob/master/examples/olm/catalog-create-subscribe.yaml (with fixed channel "4.5", because 4.4 is not available), I get the problem, that local-storage-operator errors out with needing POD_NAME environment variable.

Setting it with downwards-API, it starts at least.

It is reporting the following error though.

```
Could not create metrics Sevice","error":"failed to create or get service for metrics: services \"local-storage-operator-metrics\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>"}
```

**Comment by meibensteiner** [comment]
I think you had the same problem I have. See [#132](https://github.com/openshift/local-storage-operator/issues/132).
Did you manage to fix it?

**Comment by ibotty** [comment]
I did not fix it, but work around it: I patch the local-storage-operator deployment regularly (using homegrown git-ops we use for other stuff), so it's only down for small amounts of time.

**Comment by meibensteiner** [comment]
What is the patch you are applying?

**Comment by ibotty** [comment]
The following patch works `oc patch deployment/local-storage-operator -p "$(cat the-patch)"`
```
{
    "apiVersion": "apps/v1",
    "kind": "Deployment",
    "metadata": {
        "name": "local-storage-operator",
        "namespace": "openshift-local-storage"
    },
    "spec": {
        "template": {
            "spec": {
                "containers": [
                    {
                        "env": [
                            {
                                "name": "POD_NAME",
                                "valueFrom": {
                                    "fieldRef": {
                                        "apiVersion": "v1",
                                        "fieldPath": "metadata.name"
                                    }
                                }
                            }
                        ],
                        "name": "local-storage-operator"
                    }
                ]
            }
        }
    }
}
```
