### ISSUE TITLE
PersistentVolumeMode duplicating corev1 PersistentVolumeMode type

### ISSUE THREAD

**Issue by awels** [openshift/local-storage-operator#15]
https://github.com/openshift/local-storage-operator/blob/master/pkg/apis/local/v1alpha1/types.go#L44 is duplicating the persistent volume mode defined in corev1, which is sort of weird since corev1 is being imported in that file.

Now there may be a reason for this duplication but it seemed weird to me.

**Comment by gnufied** [comment]
Thanks for the issue. We will fix it.
