### ISSUE TITLE
Unable to deploy local-storage

### ISSUE THREAD

**Issue by j-griffith** [openshift/local-storage-operator#20]
Still seem to have a mismatch somewhere with the versioning changes that were added, not sure I thought that https://github.com/openshift/local-storage-operator/pull/19 would sync that up.

But trying to run just now I'm still seeing the same error when trying to create a new cr:

`no matches for kind "LocalVolume" in version "local.storage.openshift.io/v1alpha1
`
and it doesn't appear that the local-storage CRD is ever installed.

**Comment by gnufied** [comment]
Follow the instructions in https://github.com/openshift/local-storage-operator/pull/21 and it should work.

**Comment by j-griffith** [comment]
The combination of the new images and the last update you made to the symlinks has everything working with OLM again.  The only other thing anybody happening upon this bug needs to note is the change from "deviceNames" to "devicePaths" and the use of full path.

Doc updates for that are in #27 

Thanks @gnufied
