### ISSUE TITLE
local storage operator metrics target down after upgrade.

### ISSUE THREAD

**Issue by germanparente** [openshift/local-storage-operator#319]
Prometheus cannot scrape metrics from the local-storage-operator pod after upgrading to ocp 4.9

"lastError": "Get \"http://<local storage operator pod ip>:8383/metrics\": dial tcp <local storage operator pod ip>:8383: connect: connection refused",

 "lastError": "Get \"http://<local storage operator pod ip>:8686/metrics\": dial tcp <local storage operator pod ip>:8686: connect: connection refused",

checking the config I can verify the ip address is exactly the one where prometheus cannot connect:

local-storage-operator-76f878db87-qngn4   1/1     Running   0          11h   <local storage operator pod ip>  <some node>

The serviceMonitor is showing:

- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    creationTimestamp: "2021-11-04T08:33:19Z"
    generation: 1
    labels:
      name: local-storage-operator
    name: local-storage-operator-metrics
    namespace: openshift-local-storage
  spec:
    endpoints:
    - bearerTokenSecret:
        key: ""
      port: http-metrics
    - bearerTokenSecret:
        key: ""
      port: cr-metrics
    namespaceSelector: {}
    selector:
      matchLabels:
        name: local-storage-operator

The service is showing:

spec:
    clusterIP: <some ip>
    clusterIPs:
    - <some ip>
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http-metrics
      port: 8383
      protocol: TCP
      targetPort: 8383
    - name: cr-metrics
      port: 8686
      protocol: TCP
      targetPort: 8686
    selector:
      name: local-storage-operator
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}

But the pod is not listening at all in those ports: 8383 / 8686

Thanks.

**Comment by rgordill** [comment]
It seems there has been some changes in operator sdk, that binds now to 8080, but the monitor service still generate 8383 and 8686. See this comment: https://github.com/operator-framework/operator-sdk/blob/9ed36cc4f5c519707a067d6cf62356c7a8bc3591/website/content/en/docs/building-operators/golang/migration.md#migrate-maingo
