### ISSUE TITLE
Issue on local-storage-operator deploying with OCS

### ISSUE THREAD

**Issue by jparrill** [openshift/local-storage-operator#44]
Regarding this issue: [OCS-Operator 104 issue](https://github.com/openshift/ocs-operator/issues/104)

It still happens, could you please take a look?

**Comment by jparrill** [comment]
Checking th deployment, those URLs are pointing to the internal registry:

```
- name: PROVISIONER_IMAGE
   value: image-registry.openshift-image-registry.svc:5000/openshift/ose-local-storage-static-provisioner:v4.2.0-201909081401
 - name: DISKMAKER_IMAGE
    value: image-registry.openshift-image-registry.svc:5000/openshift/ose-local-storage-diskmaker:v4.2.0-201909091819
image: image-registry.openshift-image-registry.svc:5000/openshift/ose-local-storage-operator:v4.2.0-201909091819
```

**Comment by jparrill** [comment]
The workaround to avoid this problem is just overwrite the images with those ones:

```
quay.io/openshift/origin-local-storage-static-provisioner:4.2.0
quay.io/openshift/origin-local-storage-diskmaker:4.2.0
quay.io/openshift/origin-local-storage-operator:4.2.0
```

**Comment by gnufied** [comment]
What creates those `ose-local-storage-operator:v4.2.0-201909091819` references? for any public testing it should be fine to use quay images.

**Comment by jparrill** [comment]
It is defined in the Deployment and Replication controller, then I guess that should be the manifest that exists on OLM or something similar

**Comment by rohantmp** [comment]
@gnufied it's created via https://github.com/openshift/ocs-operator/blob/release-4.2/deploy/deploy-with-olm.yaml

**Comment by gnufied** [comment]
My catalog manifests uses quay.io images by default. I think the image version is being replaced somewhere. If intention is to use this operator with OCP and use official images shipped by ART team, then one should install this operator from redhat-operators-art `OperatorSource`.

**Comment by rohantmp** [comment]
@gnufied Is quay.io specified explicitly?

**Comment by gnufied** [comment]
It is! btw - I have updated the docs to use `OperatorSource` objects rather than explicitly creating catalog manifests.  The operatorSource also uses images from quay.io - https://github.com/openshift/local-storage-operator/blob/master/examples/olm/catalog-create-subscribe.yaml . I think OCS installation script should prefer using `OperatorSource` because that will be much closer to how final deployment will look like.
