### ISSUE TITLE
olm data needs to be updated for 4.3

### ISSUE THREAD

**Issue by jupierce** [openshift/local-storage-operator#47]
https://github.com/openshift/local-storage-operator/tree/release-4.3/manifests
file not found: manifests/4.3/image-references

**Comment by jupierce** [comment]
cc: @gnufied

**Comment by gnufied** [comment]
Thanks. I will make a fix. Is this breaking something somewhere? I don't think we added jobs in ci-operator(or what-its-new-name) for 4.3 and local-storage-operator yet.

**Comment by jupierce** [comment]
Thanks @gnufied - without this data, ART cannot build your operator for 4.3. The same rules will apply when we cut over to 4.4 and so on.
