### ISSUE TITLE
OKD 4.15 and local-storage-operator

### ISSUE THREAD

**Issue by Dubridze** [openshift/local-storage-operator#486]
Unable to install operator. Install plan failed: api-server resource not found installing CustomResourceDefinition localvolumediscoveries.local.storage.openshift.io: GroupVersionKind apiextensions.k8s.io/v1beta1, Kind=CustomResourceDefinition not found on the cluster. This API may have been deprecated and removed, see https://kubernetes.io/docs/reference/using-api/deprecation-guide/ for more information.

**Comment by dronenb** [comment]
I get the same thing when installing the local storage operator on `k3s` when following the instructions from [here](https://github.com/openshift/local-storage-operator/blob/master/docs/deploy-with-olm.md#deploy-local-storage-operator). Looks like it is probably needs to be configured to use `apiextensions.k8s.io/v1` instead...
