### ISSUE TITLE
ART build issue - invalid OLM manifest data

### ISSUE THREAD

**Issue by jupierce** [openshift/local-storage-operator#49]
`local-storage-operator/manifests/4.3/local-storage-operator.v4.3.0.clusterserviceversion.yaml does not exist as defined in art.yaml` .

**Comment by jupierce** [comment]
cc: @gnufied

**Comment by jupierce** [comment]
relates to: https://github.com/openshift/local-storage-operator/issues/47

**Comment by sosiouxme** [comment]
I think this got fixed :-)
