### ISSUE TITLE
no matches for kind "LocalVolume" in version "local.storage.openshift.io/v1"

### ISSUE THREAD

**Issue by achuzhoy** [openshift/local-storage-operator#87]
Tried to follow the instructions here:
https://github.com/openshift/local-storage-operator/blob/master/docs/deploy-with-olm.md
oc create -f create-cr.yaml fails with
error: unable to recognize "create-cr.yaml": no matches for kind "LocalVolume" in version "local.storage.openshift.io/v1"

**Comment by achuzhoy** [comment]
This was attempted on a cluster version: 4.3.0-0.nightly-2020-01-29-050742

**Comment by cdvultur** [comment]
What is the procedure to install local-storage-operator on old versions ?

**Comment by jnpacker** [comment]
Let me take a look at the Mongodb chart and see if I can track this down.

**Comment by gnufied** [comment]
Instructions for OCP installation is here - https://docs.openshift.com/container-platform/4.2/storage/persistent-storage/persistent-storage-local.html

The docs you have linked is for internal development and testing.

**Comment by ohochman** [comment]
this issue is preventing us from automating the ACM installation, as it required to add the storage from the UI..   according to https://docs.openshift.com/container-platform/4.2/storage/persistent-storage/persistent-storage-local.html 

Questions: 
(1) Is the link above it the right way to deploy MCM on OCP BM ? 
(2) Is there a way to add the storage in another way not from UI? 
(3) does the local storage is a mandatory requirement for the installation to start?

**Comment by gnufied** [comment]
You can also install operator from official redhat channels by using `oc create -f https://github.com/openshift/local-storage-operator/blob/master/examples/olm/redhat-src-catalog.yaml`. Just make sure that channel in https://github.com/openshift/local-storage-operator/blob/master/examples/olm/redhat-src-catalog.yaml#L21 matches version of OCP installing the operator on.

There is a docs bug filed to document installation process from CLI - https://bugzilla.redhat.com/show_bug.cgi?id=1800649

I dunno what you mean by ACM installation but please open BZ against Redhat if you need help.

**Comment by ElCoyote27** [comment]
I'm getting the same error on 4.5.8 specifically (following https://github.com/red-hat-storage/ocs-training/blob/master/ocp4ocs4/ocs4-install-no-ui.md)

This is a fresh 4.5.8 cluster:
```
$ oc get clusterversion
NAME      VERSION   AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.5.8     True        False         3h51m   Cluster version is 4.5.8
```

the error happens when creating the cr:
```
+ oc --overwrite=true --wait=true apply -f /home/myuserCode/GIT/virt-OCP/scripts/OCS/local-storage-namespace.yaml
namespace/openshift-local-storage unchanged
+ oc --overwrite=true --wait=true apply -f /home/myuserCode/GIT/virt-OCP/scripts/OCS/local-storage-operator.yaml
operatorgroup.operators.coreos.com/openshift-local-storage configured
+ oc --overwrite=true --wait=true apply -f /home/myuserCode/GIT/virt-OCP/scripts/OCS/local-storage-operator-sub.yaml
subscription.operators.coreos.com/openshift-local-storage-operator unchanged
+ oc --overwrite=true --wait=true apply -f /home/myuserCode/GIT/virt-OCP/scripts/OCS/local-storage-cr.yaml
error: unable to recognize "/home/myuserCode/GIT/virt-OCP/scripts/OCS/local-storage-cr.yaml": no matches for kind "LocalVolume" in version "local.storage.openshift.io/v1"
```

**Comment by ElCoyote27** [comment]
My local-store-cr.yaml is pretty simple:
```
$ cat local-storage-cr.yaml 
apiVersion: local.storage.openshift.io/v1
kind: LocalVolume
metadata:
  name: localstorage-ocs-osd
  namespace: openshift-local-storage
spec:
  nodeSelector:
    nodeSelectorTerms:
      - matchExpressions:
          - key: cluster.ocs.openshift.io/openshift-storage
            operator: In
            values:
            - ""
  storageClassDevices:
    - storageClassName: localstorage-ocs-osd-sc
      volumeMode: Block
      devicePaths:
        - /dev/disk/by-id/wwn-0x5000c50015ea71ab
        - /dev/disk/by-id/wwn-0x5000c50015ea71ac
        - /dev/disk/by-id/wwn-0x5000c50015ea71ad
        - /dev/disk/by-id/wwn-0x5000c50015ea71ae
        - /dev/disk/by-id/wwn-0x5000c50015ea71b0
        - /dev/disk/by-id/wwn-0x5000c50015ea71b1
        - /dev/disk/by-id/wwn-0x5000c50015ea71b2
        - /dev/disk/by-id/wwn-0x5000c50015ea71b3
        - /dev/disk/by-id/wwn-0x5000c50015ea71b4
        - /dev/disk/by-id/wwn-0x5000c50015ea71ba
        - /dev/disk/by-id/wwn-0x5000c50015ea71bb
        - /dev/disk/by-id/wwn-0x5000c50015ea71bc
        - /dev/disk/by-id/wwn-0x5000c50015ea71bd
        - /dev/disk/by-id/wwn-0x5000c50015ea71be
        - /dev/disk/by-id/wwn-0x5000c50015ea71c0
        - /dev/disk/by-id/wwn-0x5000c50015ea71c1
        - /dev/disk/by-id/wwn-0x5000c50015ea71c2
        - /dev/disk/by-id/wwn-0x5000c50015ea71c3
        - /dev/disk/by-id/wwn-0x5000c50015ea71c4
        - /dev/disk/by-id/wwn-0x5000c50015ea71ca
        - /dev/disk/by-id/wwn-0x5000c50015ea71cb
        - /dev/disk/by-id/wwn-0x5000c50015ea71cc
        - /dev/disk/by-id/wwn-0x5000c50015ea71cd
        - /dev/disk/by-id/wwn-0x5000c50015ea71ce
```
